# Generated by Django 5.0.4 on 2024-09-03 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0026_auto_20240807_1216'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='choice_response',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='scale_range',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='is_published',
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(default='Default text', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),  # Make the field optional
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('short-answer', 'Short answer'), ('paragraph', 'Paragraph'), ('multiple-choice', 'Multiple choice'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Dropdown')], max_length=50),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='target_audience',
            field=models.CharField(choices=[('students', 'Students'), ('alumni', 'Alumni')], max_length=20),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Alumni.question')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='student_materials/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
