# Generated by Django 5.0.4 on 2024-09-03 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0027_remove_response_choice_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(default='Default text', max_length=255),
        ),
        migrations.AlterField(
            model_name='survey',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
